default_install_hook_types: [pre-commit, pre-push]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/TekWizely/pre-commit-golang
      rev: v1.0.0-rc.1
      hooks:
          - id: go-mod-tidy-repo
            stages: [commit]
          - id: golangci-lint-repo-mod
            stages: [commit]
          - id: go-test-mod
            stages: [push]
